#include"./library/src/stm32f10x_it.c"
#include"./library/src/stm32f10x_nvic.c"
#include"./library/src/stm32f10x_gpio.c"
#include"./library/src/stm32f10x_flash.c"
#include"./library/src/stm32f10x_rcc.c"
#include"./library/src/stm32f10x_adc.c"
#include"./library/src/stm32f10x_can.c"
#include"./library/src/stm32f10x_dma.c"
#include"./library/src/stm32f10x_exti.c"
#include"./library/src/stm32f10x_iwdg.c"
#include"./library/src/stm32f10x_rtc.c"
#include"./library/src/stm32f10x_systick.c"
#include"./library/src/stm32f10x_wwdg.c"
#include"./library/src/stm32f10x_usart.c"
#include"./library/src/stm32f10x_tim.c"
#include"./library/src/stm32f10x_bkp.c"
#include"./library/src/stm32f10x_pwr.c"

/*
#include"./library/src/stm32f10x_lib.c"
#include"./library/src/stm32f10x_i2c.c"
#include"./library/src/stm32f10x_spi.c"
#include"./library/src/stm32f10x_tim1.c"								   
*/

#include "stm32f10x_lib.h"
#include "stdio.h"
